apiVersion: batch/v1
kind: Job
metadata:
  name: import-osm-job
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: import-osm-job
        image: gcr.io/smart-nnov/bitnami-postgis:eyusupov4
        command: ["pg_restore", "/import/osm.dump.gz", "--schema=public", "-d", "gis_test"]
        workingDir: /home/dev
        securityContext:
          privileged: true
        env:
        - name: PGUSER
          value: "postgres"
        - name: PGPASSWORD
          value: "smart-city-nnov!"
        - name: PGHOST
          value: 10.63.245.54
        volumeMounts:
        - mountPath: /import
          name: import
      volumes:
      - name: import
        persistentVolumeClaim:
          claimName: data-pvc
